kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
    name: rootapp
    namespace: argocd
    finalizers:
        - resources-finalizer.argocd.argoproj.io
spec:
    project: default
    source:
        path: helm
        repoURL: https://github.com/fsedano/argocd-15-min.git
        targetRevision: HEAD
    destination:
        namespace: production
        server: https://kubernetes.default.svc
    syncPolicy:
        automated:
            selfHeal: true
            prune: true
            
